FROM golang:1.23-alpine AS api-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o barf-api ./cmd/http

FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY web/package*.json ./
RUN npm ci
COPY web/ .
RUN npm run build

FROM alpine:3.19
RUN apk --no-cache add ca-certificates nginx
RUN adduser -D -g 'www' www && \
    mkdir /www && \
    chown -R www:www /var/lib/nginx && \
    chown -R www:www /www

WORKDIR /app
COPY --from=api-builder --chmod=755 /app/barf-api .
COPY --from=frontend-builder --chmod=755 /app/dist /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000 8080

CMD ["sh", "-c", "nginx && ./barf-api"]