
services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "2345:2345" # Debug port
    environment:
      - DB_HOST=postgres
      - DB_USER=barf
      - DB_PASSWORD=secret
      - DB_NAME=barf_db
      - ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=barf
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=barf_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
volumes:
  postgres_data:
  go-mod-cache:
